"""
modules/orders/models.py

Responsibility
--------------
Defines the two ORM models for the order subsystem — Order and OrderItem —
following the same conventions as every other model in the codebase.

Key architectural rules:
1. OrderItem stores snapshot fields (product_name, product_sku, unit_price)
   at the time of ordering — prices and product names change over time, but
   order records must be immutable.
2. `line_total` is stored (not computed) for historical accuracy.
3. Optimistic concurrency via a `version` field on Order.
4. Order status transitions are NOT enforced at the model level — they are
   enforced in the service layer via a transition map (see OrderService).
5. Soft-delete is NOT used — orders are immutable business records.

Relationship rules:
- Order ↔ OrderItem: one-to-many (items are cascade-deleted with the order).
- OrderItem → Product: many-to-one (informational reference only;
  product_name/product_sku are snapshotted on the item).
- OrderItem → Warehouse: many-to-one (which warehouse fulfilled this item).
"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import CheckConstraint, ForeignKey, Numeric, String, Text, func
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.modules.orders.constants import OrderStatus, PaymentStatus

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.models.product import Product
    from app.models.user import User
    from app.modules.inventory.models import Warehouse


class Order(Base):
    """
    The core order entity — a customer's purchase request.

    Every order follows a strict lifecycle enforced by OrderService:
    PENDING -> CONFIRMED -> PROCESSING -> SHIPPED -> DELIVERED
    Cancellation is only allowed before SHIPPED.
    Returns/Refunds are only allowed after DELIVERED.

    Notes on specific columns:
    - `order_number`: Human-readable, unique identifier (e.g. "ORD-20260730-A1B2C3D4").
      Generated by the service layer, not the database.
    - `customer_id`: References the User who placed the order.
    - `created_by`/`updated_by`: Audit trail — who created/updated the order.
    - `version`: Optimistic concurrency lock. Read the current version, apply a
      change, and only the write that matches the current version succeeds.
    - `reserved_until`: When the stock reservation expires. Null until reserved.
    - `cancel_reason`: Free-text reason for cancellation. Null until cancelled.
    - All monetary fields use `Numeric(12, 2)` — fixed-point decimal for currency.
    """

    __tablename__ = "orders"
    __table_args__ = (
        CheckConstraint("subtotal >= 0", name="order_subtotal_non_negative"),
        CheckConstraint("tax >= 0", name="order_tax_non_negative"),
        CheckConstraint("shipping_cost >= 0", name="order_shipping_non_negative"),
        CheckConstraint("discount >= 0", name="order_discount_non_negative"),
        CheckConstraint("total >= 0", name="order_total_non_negative"),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)

    order_number: Mapped[str] = mapped_column(
        String(32), unique=True, index=True, nullable=False
    )

    customer_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", name="fk_orders_customer_id_users", ondelete="RESTRICT"),
        index=True,
        nullable=False,
    )

    status: Mapped[OrderStatus] = mapped_column(
        SAEnum(
            OrderStatus,
            name="order_status",
            native_enum=True,
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        default=OrderStatus.PENDING,
        index=True,
        nullable=False,
    )

    # --- Monetary fields ---------------------------------------------------
    subtotal: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00")
    )
    tax: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00")
    )
    shipping_cost: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00")
    )
    discount: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00")
    )
    total: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False, default=Decimal("0.00")
    )

    # --- Payment -----------------------------------------------------------
    payment_status: Mapped[PaymentStatus] = mapped_column(
        SAEnum(
            PaymentStatus,
            name="payment_status",
            native_enum=True,
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        default=PaymentStatus.UNPAID,
        index=True,
        nullable=False,
    )

    # --- Workflow fields ---------------------------------------------------
    reserved_until: Mapped[datetime | None] = mapped_column(nullable=True)
    cancel_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # --- Audit fields ---------------------------------------------------
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Optimistic concurrency — incremented on every write.
    version: Mapped[int] = mapped_column(default=1, nullable=False)

    created_by: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", name="fk_orders_created_by_users"), nullable=False
    )
    updated_by: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", name="fk_orders_updated_by_users"), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), index=True, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # --- Relationships ---------------------------------------------------
    items: Mapped[list["OrderItem"]] = relationship(
        "OrderItem",
        back_populates="order",
        lazy="selectin",
        cascade="all, delete-orphan",
        order_by="OrderItem.created_at",
    )

    def __repr__(self) -> str:
        return (
            f"<Order id={self.id} number={self.order_number} "
            f"status={self.status.value} total={self.total}>"
        )


class OrderItem(Base):
    """
    A single line item on an order.

    Snapshots product_name, product_sku, and unit_price at the time of
    ordering — these fields are immutable after creation and preserve the
    commercial reality of the transaction even if the product catalog is
    later updated.

    `line_total` is stored (not computed) for historical accuracy. It equals
    `quantity * unit_price` at creation time, but is an independent field so
    that future discounts applied at the item level (rather than order level)
    can be recorded without ambiguity.

    Relationship rules:
    - `order_id`: FK to orders with CASCADE delete — if an order is deleted,
      its items are deleted too.
    - `product_id`: FK to products — informational reference only.
    - `warehouse_id`: FK to warehouses — which warehouse fulfilled this item.
    """

    __tablename__ = "order_items"
    __table_args__ = (
        CheckConstraint("quantity > 0", name="order_item_quantity_positive"),
        CheckConstraint("unit_price >= 0", name="order_item_unit_price_non_negative"),
        CheckConstraint("line_total >= 0", name="order_item_line_total_non_negative"),
    )

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)

    order_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("orders.id", name="fk_order_items_order_id_orders", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )

    product_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("products.id", name="fk_order_items_product_id_products", ondelete="RESTRICT"),
        index=True,
        nullable=False,
    )

    # Snapshot fields — preserved at order time, never updated.
    product_name: Mapped[str] = mapped_column(String(255), nullable=False)
    product_sku: Mapped[str] = mapped_column(String(64), nullable=False)

    warehouse_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey(
            "warehouses.id",
            name="fk_order_items_warehouse_id_warehouses",
            ondelete="RESTRICT",
        ),
        index=True,
        nullable=False,
    )

    quantity: Mapped[int] = mapped_column(nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False
    )
    line_total: Mapped[Decimal] = mapped_column(
        Numeric(12, 2), nullable=False
    )

    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(), nullable=False
    )

    # --- Relationships ---------------------------------------------------
    order: Mapped["Order"] = relationship("Order", back_populates="items")
    product: Mapped["Product"] = relationship("Product")  # noqa: F821
    warehouse: Mapped["Warehouse"] = relationship("Warehouse")  # noqa: F821

    def __repr__(self) -> str:
        return (
            f"<OrderItem id={self.id} order={self.order_id} "
            f"product={self.product_id} qty={self.quantity}>"
        )
